name: flutter_application_2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.8
  mailer: ^6.0.0
  flutter_svg: ^2.0.5
  spider: ^4.2.2
  sqflite: ^2.2.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
